language: go
sudo: false
go: 1.5
before_script:
  - nvm install 4.0
  - |-
    echo "{\"token\": \"$GITHUB_TOKEN\"}" > ui/.tsdrc
script: make dist

addons:
  sauce_connect: true

# Sauce Labs API keys + GitHub token for tsd + GitHub token for releases
env:
  global:
    - secure: "rdb4hcgIpxHZ7bj/33HE8x/lx908tyHiLazdw2neW48i5sicIgq5tmQP/eE3323Ldr35Mw086y0LaM0NVOLasVYIZylxGSDVc+0Mw3JFEs1h/2UNcKPwqnsGwvnilnGbRMXw4HEbpWkDHVBtTJUbjXdMTdyDImznpTmKi0SmIFLSP/ZMfKvjvihr2xnlcVxkNZw9Mq+D6UGptjKjwFSeK1WxSTvsbzYP465epB7nl2VimTQZfY3TjnaP48a6AxjGtXC0iCaeb17Ez5dKgVEnthdNxn9Ed4FszGPfE9NDAqx90oLLI1UvigNjUkClYE2X0ElnIRSSZqjdClSpYK2i3Yai3/q4UW6Qg8ZwJRTjx3SoDibw3t7CCn0lE0VPhDElynaV9BLv5FWiGe7iE6y+/ynSaqMLIidBY3ZzzEKLnWOr0lnlg2VS05/6wS6ACjQlr1B0FCJNBVXdvjN8ETw6Lk0qjEVQy28ccJr6zbIJZH7qfXxZlBgK0IP/t4Y769983BVLTNtyQB6GmKUvOMNPTkhJ440N4IaSW13hbV8ncFOPGKQ1TVeg/EWG6vK+Y2fT7PCSOQITlaQTNeb98FAU+pP3f3oSJ07b3TZbkKxzRDH6i0eO0HrBQSMTnbMzEoGKS/zXNowC6ZhS+heIADi2vbJ/ESpmsYeb5yZZ2dxfedU="
    - secure: "DvUdsSBMbNUm7/lc1MUs9kbffyoztsBJgYx8sk4fl+lC7vSReuz5C0zGxyl9bkZ1JogrfMQQSwKpY1K7ZeLJa9Xse0MZ8U1HuPGVJ5THCUTEO9uWKF5Vulo9ZxCrA7Cun1UaSJzadBeETPPwSSLfqNZ7Raz/7Dyj+NG/Sgb2ENyHR7d8nXnaFNkj2ac3hk2DT9sW6Dbgoj6MGDJRznRUJSAiN+UtNHemgZFIOgHjW8n0juub2Z+sXjRIflMzCJ3cXWvKAYI5HF7mcfO5b2wx6bgctZVVhilnzmyOBSjLj2NjDr1L7SXPkXIVOi5yLSMUG5dX8oUA3iHIsf9LNxokEj2o5cOIkUTZKOI2saeBHo5C7vKK/UbYEzB8x/BDQIUj2/mOqWsaVYu9hCNqN3s5uVlvfn7cSiB6/js9nEPKMJztx+q7UfL2iNlCl8sLWUU875Kxyz5n0EGbu2bvCiDldGzfH7Kq/yi+4wv3TWrsI2s8D90nrB1NBUW58rQgfj6c1zvICaepi+2l3uSrbXNHK4sEYB2hUgTwbIgsVrfn+v3uaPKhKiH287ObIdO97/tbUjPbVKBHFmPwhS7HXoQdnPjnNMguHVvq8wpQ1PnGd4eU1zaNmFFtiQi/HhREacxtveapnNrKmyI0NXdvk9u6LC5d/pe1OhBBpphDAuz7KFw="
    - secure: "lvwdVcmox/uXES03idEuczSFZcpiCzvq0Ci21ncZX+YUl9soUtjEFriWQVaru/WeSzAZtXnK8i8K1wtVvEUHsYRkDHM/aQKGnMobd6iNKn8WZiGQP18R20QzNBj8Iq/TGokNbd+SbpKZS2ZRhJRKzSamptM2oF88AmuuTaFdvoMnn243GXv1tCVeldgTOt/Y8CCEpNvkS0X9NLL78UfI0lbGi99SP2apSTSIMfaRRUj0WUuONkmESpZ7Ykvf07QrqR+4ujoUO4SyIgpjOLhgiprSuMFco2zZ8YdDHsHQg3ahc993bDNAtrU87mmmWJLcVFLhF6XAdJyL7at3flUxu2nLQz+UmldBRbBs9bYkIes5fxjN7hExPn8H/B4GpsxIhNfNTC0w8J6Z1nqYEKAkE+y+mRhD8GTYRbcAcVIKYoatZC+K4vK+U1cy+C6AA8Yc9KLDKW9r9LNVl+oWAc5nwl/w8nRE5iO0dacv11oZSOmOcGkp/ok+58wR4SJUFN3NVZ2JPQdPk+lIoI980hHYwoWLb/NuyvdSTDO5snAe2iH8mv4xyNQBO1yLSe+BQPW07RK+YDJEMorp1vZskm+xW6CQ4fLqFzUqQoapQKN3k1oMlv7OHpR2rHywkzNCjnvVdSBbT4xkENvER/ZW2yohX36CdpNygXPP8zAt3I89Fj4="

deploy:
  provider: releases
  api_key:
    secure: bah5ym2KWYVmwsHKUTM5DPPxKaQmMWvK2R+n2CiJSLpKGqnIlRRDi1mFDVOwFwcKP5hcQ+ByarrG01sP3F/WbWM2/oAYVZsGWEuZD2t/sxM1a27XeSGwj06pjXvNhdjbxLBGYjGNt1Hu811i0HNci/gK1yo+Bg0ZYqA73bHxXOPefRCsmTvThTSaNjBD7i9z5joUnphXwUSt8kaDVGsG6lVVHcYSkLJesi4b29O+U2vMwqtTpWbxw/hopKsFDUWutK6XadTdqcj7gxxYFYI3KZyWo2Y23VDkahEAPjNOh/ld8R3sJUnVBSJV9O8OJwgGfZqhB26IGtdiOHyCF+xEu8vXMd99GJqB0H5n6B5nps+5PV3Yf77IyG9q7bJgeYoxzKWZzngd7umXS9I+w+nff/RhmPcl9G5tv5lbC522SqRMo8DKmMgANAoMcpgQp5AANkwLBoyKuyuyxL7y1LNPHnQVYnt9hlgiKKkcNDCvzKevHVfEX6/qm6EdfCegZPtXByO2ZBfNxIBKiYzTAQBBc1reA8coiH/NxZIaxP7Cd01ONoMLDmYuNz6pmxeNibDsbQRpPwHv5ImmuxvCUJsCYZTmDzQKKP5oWK6tBG+E1d3bCkx/yeK3ZisCbcfkauM8oppX4FpqvW2d7CRfwnP+XazhxDHirkwUY9ASWkwmwog=
  file: dist/go-top.tar.gz
  skip_cleanup: true
  on:
    repo: olivierlemasle/go-top
    tags: true
