language: go
sudo: false
go: 1.5
install: true
before_script: ui/install.sh

addons:
  sauce_connect: true

env:
  global:
    - secure: "rdb4hcgIpxHZ7bj/33HE8x/lx908tyHiLazdw2neW48i5sicIgq5tmQP/eE3323Ldr35Mw086y0LaM0NVOLasVYIZylxGSDVc+0Mw3JFEs1h/2UNcKPwqnsGwvnilnGbRMXw4HEbpWkDHVBtTJUbjXdMTdyDImznpTmKi0SmIFLSP/ZMfKvjvihr2xnlcVxkNZw9Mq+D6UGptjKjwFSeK1WxSTvsbzYP465epB7nl2VimTQZfY3TjnaP48a6AxjGtXC0iCaeb17Ez5dKgVEnthdNxn9Ed4FszGPfE9NDAqx90oLLI1UvigNjUkClYE2X0ElnIRSSZqjdClSpYK2i3Yai3/q4UW6Qg8ZwJRTjx3SoDibw3t7CCn0lE0VPhDElynaV9BLv5FWiGe7iE6y+/ynSaqMLIidBY3ZzzEKLnWOr0lnlg2VS05/6wS6ACjQlr1B0FCJNBVXdvjN8ETw6Lk0qjEVQy28ccJr6zbIJZH7qfXxZlBgK0IP/t4Y769983BVLTNtyQB6GmKUvOMNPTkhJ440N4IaSW13hbV8ncFOPGKQ1TVeg/EWG6vK+Y2fT7PCSOQITlaQTNeb98FAU+pP3f3oSJ07b3TZbkKxzRDH6i0eO0HrBQSMTnbMzEoGKS/zXNowC6ZhS+heIADi2vbJ/ESpmsYeb5yZZ2dxfedU="
    - secure: "DvUdsSBMbNUm7/lc1MUs9kbffyoztsBJgYx8sk4fl+lC7vSReuz5C0zGxyl9bkZ1JogrfMQQSwKpY1K7ZeLJa9Xse0MZ8U1HuPGVJ5THCUTEO9uWKF5Vulo9ZxCrA7Cun1UaSJzadBeETPPwSSLfqNZ7Raz/7Dyj+NG/Sgb2ENyHR7d8nXnaFNkj2ac3hk2DT9sW6Dbgoj6MGDJRznRUJSAiN+UtNHemgZFIOgHjW8n0juub2Z+sXjRIflMzCJ3cXWvKAYI5HF7mcfO5b2wx6bgctZVVhilnzmyOBSjLj2NjDr1L7SXPkXIVOi5yLSMUG5dX8oUA3iHIsf9LNxokEj2o5cOIkUTZKOI2saeBHo5C7vKK/UbYEzB8x/BDQIUj2/mOqWsaVYu9hCNqN3s5uVlvfn7cSiB6/js9nEPKMJztx+q7UfL2iNlCl8sLWUU875Kxyz5n0EGbu2bvCiDldGzfH7Kq/yi+4wv3TWrsI2s8D90nrB1NBUW58rQgfj6c1zvICaepi+2l3uSrbXNHK4sEYB2hUgTwbIgsVrfn+v3uaPKhKiH287ObIdO97/tbUjPbVKBHFmPwhS7HXoQdnPjnNMguHVvq8wpQ1PnGd4eU1zaNmFFtiQi/HhREacxtveapnNrKmyI0NXdvk9u6LC5d/pe1OhBBpphDAuz7KFw="
